image: qmkfm/qmk_firmware

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  tags:
  - docker
  - linux
  script:
  - make
  artifacts:
    name: "$CI_COMMIT_REF_SLUG-${CI_COMMIT_SHA:0:8}"
    paths:
    - 'whitefox-*.bin'
