image: registry.alebastr.su/alebastr/qmk-whitefox-keymap
variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  tags:
  - docker:linux
  script:
  - make
  artifacts:
    name: "$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
    paths:
    - 'whitefox-*.bin'

build-docker:
  stage: build
  image: docker:stable
  services:
  - docker:dind
  tags:
  - docker:linux
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_DRIVER: overlay2
    GIT_SUBMODULE_STRATEGY: none
  only:
    changes:
    - docker/*
    refs:
    - master
  script:
  - cd docker
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build -t $CI_REGISTRY_IMAGE:latest .
  - docker push $CI_REGISTRY_IMAGE:latest
