image: qmkfm/qmk_firmware

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  tags:
  - docker
  - linux
  script:
  - make
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
    - 'whitefox-*.bin'
